data:
  filepath: ./data/1.txt_graph

variables:
  truncate_range: 1000

nn:
  num_of_layers: 4

train:
  epochs: 10
  epoch_test: 100
  lr: 0.0001
  milestones: 
    - 400
    - 1000

batch: 3

test:
  batch_size: 3